### ISSUE TITLE
Fix FRAX<>WGLMR APR on Stellaswap

### ISSUE THREAD

**Issue by nightwing-yb** [yield-bay/bay-watcher#14]

**Comment by 0xSonOfNeptune** [comment]
On the stella dashboard, the rewards is shown as 1825 STELLA/day, but according to the [contract](https://moonscan.io/address/0xF3a5454496E26ac57da879bf3285Fa85DEBF0388#readContract), we are getting rewards as 1369 STELLA/day (`60*60*24*15843956043956043/10^18 = 1,368.917802`)
<img width="614" alt="Screenshot 2022-08-24 at 1 14 25 PM" src="https://user-images.githubusercontent.com/94821659/186360745-214d62b4-1b28-482e-9c20-330017aeb4a0.png">


<img width="1468" alt="Screenshot 2022-08-24 at 1 12 44 PM" src="https://user-images.githubusercontent.com/94821659/186360388-649a0c3b-5843-4bba-a806-46f7ea6d9f1e.png">

**Comment by 0xSonOfNeptune** [comment]
By using allocPoint & stellaPerSec, we get the value 1825:
```
(36/455)*60*60*24*267000000000000000/10^18 = 1,825.223736
```
